### ISSUE TITLE
Will we have something similar for Vapor 2 -> Vapor 3?

### ISSUE THREAD

**Issue by j-nguyen** [vapor/migrator#10]
What the title states. This was really useful when we had to transition from Vapor 2 to Vapor 3. Curious to see if you guys are going to be doing the same thing?

**Comment by tanner0101** [comment]
I'm planning on writing a migration _guide_ (that will be on the docs). However I don't know if there will be time to create another package like this one.

**Comment by j-nguyen** [comment]
That's perfect as well! Thanks, and can't wait for the official release of Vapor 3!
