### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by hotbit9** [vapor/migrator#5]
It takes more than 2hrs and give an error while trying to update my project:

> vapor update:

```
Error: backgroundExecute(code: 1, error: "warning: refname \'1.1.0\' is ambiguous.\nswift-package: error: /var/folders/g5/hsn80w4124s8p27f5s376qn40000gn/T/TemporaryFile.aUpPNs.swift:25:2: error: argument \'pkgConfig\' must precede argument \'providers\'\n        pkgConfig: \"libcurl\"\n        ^\nexit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --driver-mode=swift -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /var/folders/g5/hsn80w4124s8p27f5s376qn40000gn/T/TemporaryFile.aUpPNs.swift -fileno 12\n", output: "Fetching https://github.com/vapor/migrator.git\nFetching https://github.com/vapor/fluent-provider.git\nFetching https://github.com/vapor/leaf-provider.git\n")
```

**Comment by tanner0101** [comment]
> `pkgConfig: \"libcurl\"\n` 

This must be coming from a different dependency, none of Vapor's packages depend on libcurl.

**Comment by hotbit9** [comment]
I have removed the non Vapor dependency and stills not working. After hours trying I just can't understand how it should work. A lack of proper documentation may be the issue. It may work for little projects but not to more complex ones. I guess I will have to build my project from scratch though.

**Comment by tanner0101** [comment]
Have you removed your `Package.pins` file? If not, it may still be pulling in the other dependency.

**Comment by hotbit9** [comment]
Removed now and update completes. Now getting error to import Migration saying it can't be found.. But it's there..

**Comment by loganwright** [comment]
@fabrijp import migrator, not migration 👍 

https://github.com/vapor/migrator#3-import-migrator
