### ISSUE TITLE
Instruction clarity and expectations on steps…

### ISSUE THREAD

**Issue by marc-medley** [vapor/migrator#6]
Some additional clarity and information on the README.md steps would be helpful.  

It seemed like Ray Wenderlich's [Server Side Swift with Vapor: Getting Started](https://videos.raywenderlich.com/screencasts/509-server-side-swift-with-vapor-getting-started) tutorial listed on [vapor.university](http://vapor.university/) would be good trial run for a first time user of the _"Vapor 1 -> 2 Migrator"_.  The tutorial is a simple, simple Vapor 1.0 web example.

Here's what I encountered …

Step 1. Step 1. Edit `Package.swift` 

… looks straight forward

Question: Does the migration utility have any "earliest" from version requirement? e.g. Is the Vapor 1.0 OK as a migration starting point?

Question: Should the following, existing line also be updated in addition to adding `.Package(url: "https://github.com/vapor/migrator.git", majorVersion: 1)` ?

```
.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 0)
```  

Step 2. Run `vapor update`

Question: how long is `vapor update` expected to take? So far, going on 3 hours on the simple getting started tutorial and still running.  This seem like a really looooong time for "updating dependencies".

> Update: after changing `.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 0)` to `.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 2)` in `Package.swift`, then `vapor update` ran to completion is a short amount of time.

Step 3. Use `import Migrator`

Question: Add `import Migrator` in which files? All /App/* files? Any other actions or further edits required after the `import`?

> Update: Adding `import Migrator` gives an error message "Cannot load module 'migrator' as 'Migrator'".  So, I switched to using lower case:
> ``` swift
> import migrator
> ```

**Comment by tanner0101** [comment]
Thanks for the detailed report. We will add this to the readme.

1: `.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1)` is good
2: It should take seconds. This means you have a dependency that cannot be resolved. Unfortunately SPM has a bug right now that causes an infinite loop. :(
3: Use `@_exported import Migrator` in just one file of your project.

**Comment by loganwright** [comment]
Thanks @marc-medley updated to be a bit more clear 👍
